---
- hosts: webserver
  remote_user: ubuntu
  become: yes
  gather_facts: yes  # Include gathering facts
  tasks:
    - name: Gather facts
      setup:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
